### ISSUE TITLE
Cross-compilation of BASICLU

### ISSUE THREAD

**Issue by amontoison** [ERGO-Code/basiclu#2]
I try to compile `basiclu` with `Yggdrasil` (https://github.com/JuliaPackaging/Yggdrasil/pull/3342) to do a Julia artifact but I have some issues with `clock_gettime` routine. Is it possible to update this routine ?

**Comment by lschork2** [comment]
I have added a compile time flag BASICLU_NOTIMER to disable calls to clock_gettime(). The timer is only needed to report statistics. Turning it off does not affect the computations. I think the timing statistics are only needed for development, so you can probably turn them off on all platforms.

**Comment by amontoison** [comment]
Thanks !
