### ISSUE TITLE
Standalone library for maxvolume

### ISSUE THREAD

**Issue by amontoison** [ERGO-Code/basiclu#3]
Thanks @lschork2 for the update of the Julia interface !

I would like to use BASICLU with [Krylov.jl](https://github.com/JuliaSmoothOptimizers/Krylov.jl) to test basis preconditioning.
Is it possible to have a dynamic library for `maxvolume` routine (example folder) such that I can call it from Julia ?

**Comment by lschork2** [comment]
I will move the maxvolume code into the basiclu library and add a Julia wrapper. It will take me a few days.

**Comment by amontoison** [comment]
Thanks !
I begin to do a Julia module based on your interface to directly use the future artifact `basiclu_jll`.
I will send you an invitation. You could move it in `ERGO-Code` organization and potentially do an official Julia package in the future.

**Comment by lschork2** [comment]
That's great, thanks. I will check if I can move it into `ERGO-Code` because I am not affiliated to the University of Edinburgh anymore. I am just allowed to maintain my old code.

I have moved the maxvolume code into the library and added a Julia wrapper.

I think I will rewrite the `basiclu_obj_` interface. There are some issues at the moment (it does not allow matrices of dimension 0) and I want to prevent the user from accessining the `ixstore` and `xstore` arrays directly. I would then also update the Julia interface to use the new (and safer) C interface.

**Comment by amontoison** [comment]
I can move it into `JuliaSmoothOptimizers` organization otherwise if it's easier for you and give you the permissions.

Thanks for the Julia wrapper of the `maxvolume` code. I tested with my package `Krylov.jl` today and it's a very good preconditioner !

For the Julia interface, you have two similar structure `BLU` and `basiclu_object` and an issue is that we cannot use the `solve` function for `obj` returned  by `maxvolume_basis`.

**Comment by lschork2** [comment]
Yes, if you could move it into `JuliaSmoothOptimizers` would be good.

Regarding the Julia interface, I want to rewrite it using only the `basiclu_object` structure. The difference between the two is that `BLU` has all its memory allocated in Julia. The C code uses reverse communication to reallocate. I thought this to be nice originally, but it gets awkward on the C side and for the maxvolume code I haven't even implemented it anymore. I hope I will find time on the weekend to do this.

**Comment by amontoison** [comment]
I moved the package into `JuliaSmoothOptimizers` : [BasicLU.jl](https://github.com/JuliaSmoothOptimizers/BasicLU.jl) and I registered it as an official Julia module.

Take your time for updating the Julia interface, I can do what I want with the actual version of the interface.
You moved the maxvolume code into the library and added a Julia wrapper for it is more than what I expected !

**Comment by lschork2** [comment]
I finally managed to reimplement the Julia interface. The new version consistently uses one `struct basiclu_object` for all functions and simplifies setting parameters and getting info values. It is not compatible to the old version, however.

Maybe you can test it (branch `julia-interface`) and let me know if there is anything that needs fixing/improvement. I will merge it into master then.

**Comment by amontoison** [comment]
Thanks @lschork2 !
Wow, you completely reimplemented the Julia interface :open_mouth: 

I have some fixing/improvements in mind :

- Add the possibility to switch between the artifact `basiclu_jll` and our own library of BASICLU. 
```julia
using Libdl

if haskey(ENV, "JULIA_BASICLU_LIBRARY_PATH")
  const libbasiclu = joinpath(ENV["JULIA_BASICLU_LIBRARY_PATH"], "libbasiclu.$dlext")
else
  using basiclu_jll
end
```
- Add an in-place `solve` function similar to `ldiv!(F, b)` or `ldiv!(y, F, b)` with `F` a Julia `basiclu_object`.
If I do a basis preconditioning for example , I will like to do efficient operators that models `B⁻¹ * v`, `B⁻ᵀ * v` or `(BBᵀ)⁻¹ * v` and not allocate new vectors at each matrix-vector product. 
- Update the version of BASICLU in `config.mk` :smiley: .

**Comment by lschork2** [comment]
Thanks for the feedback. I have added it and merged julia-interface into master.

**Comment by amontoison** [comment]
Thanks! I recompiled an artifact `basiclu_jll` for the new version 2.2.0 : https://github.com/JuliaPackaging/Yggdrasil/pull/3533.
I will update the package [BasicLU.jl](https://github.com/JuliaSmoothOptimizers/BasicLU.jl) next week and test the new features.
